DROP TABLE IF EXISTS PERSON CASCADE;
CREATE TABLE PERSON(id SERIAL, uuid VARCHAR(200) UNIQUE NOT NULL, firstname VARCHAR(30) NOT NULL, lastname VARCHAR(30) ,email VARCHAR(50),
                      contact_number VARCHAR(30) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255)  ,PRIMARY KEY(id));

DROP TABLE IF EXISTS ACCOUNT CASCADE;
CREATE TABLE ACCOUNT(id SERIAL, uuid VARCHAR(200) UNIQUE NOT NULL,account_type VARCHAR(255), balance INTEGER, PRIMARY KEY (id));

DROP TABLE IF EXISTS STATEMENT CASCADE;
CREATE TABLE STATEMENT(id SERIAL,uuid VARCHAR(200) UNIQUE NOT NULL, debit INTEGER, credit INTEGER , date DATE, PRIMARY KEY (id));

